package baseDatos;
// Generated Nov 15, 2018 2:04:50 PM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Libro generated by hbm2java
 */
public class Libro implements java.io.Serializable {

	private Integer idLibro;
	private String isbn;
	private String titulo;
	private String autores;
	private Integer ano;
	private Set prestamos = new HashSet(0);

	public Libro() {
	}

	public Libro(String isbn, String titulo, String autores, Integer ano, Set prestamos) {
		this.isbn = isbn;
		this.titulo = titulo;
		this.autores = autores;
		this.ano = ano;
		this.prestamos = prestamos;
	}

	public Integer getIdLibro() {
		return this.idLibro;
	}

	public void setIdLibro(Integer idLibro) {
		this.idLibro = idLibro;
	}

	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public String getAutores() {
		return this.autores;
	}

	public void setAutores(String autores) {
		this.autores = autores;
	}

	public Integer getAno() {
		return this.ano;
	}

	public void setAno(Integer ano) {
		this.ano = ano;
	}

	public Set getPrestamos() {
		return this.prestamos;
	}

	public void setPrestamos(Set prestamos) {
		this.prestamos = prestamos;
	}

	@Override
	public String toString() {
		return "Libro [idLibro=" + idLibro + ", isbn=" + isbn + ", titulo=" + titulo + ", autores=" + autores + ", ano="
				+ ano + "]";
	}

}
